language: python

python:
    - 2.7
    - 3.3
    - 3.4

before_install:
    - export PYTHON_MAJOR=${TRAVIS_PYTHON_VERSION:0:1}
    - if [[ $PYTHON_MAJOR == '3' ]]; then export P="3"; fi

install:
    - sudo apt-get install -qq cython${P}
    - sudo apt-get install -qq zookeeper
    - pip install -r requirements/base.txt
    - pip install .


before_script:
    - export ZOOKEEPER_PATH=/usr/share/java

script:
    - mkdir -p tmp
    - pushd tmp
    - nosetests --with-lymph lymph
    - popd

notifications:
    email: false
